fos_elastica:
    serializer: ~
    clients:
        default: { host: elasticsearch, port: 9200 }
    indexes:
        workshop: #doc
            settings:
                analysis:
                    filter:
                        regexp_filter:
                            type: "ngram"
                            min_gram: 3
                            max_gram: 30
                    analyzer:
                        index_regexp:
                            type: "custom"
                            tokenizer: "whitespace"
                            filter: ["lowercase", "regexp_filter"]
                        search_regexp:
                            type: "custom"
                            tokenizer: "whitespace"
                            filter: ["lowercase"]
            types:
                shop:
                    serializer:
                        groups: ["workshop1"]
                    persistence:
                        driver: orm
                        model: ProductBundle\Entity\Product
                          #The _all field allows you to search for values in documents
                          #without knowing which field contains the value.
                    indexable_callback: 'shouldBeElasticSearchIndexable'
                    _all:
                        enabled: false

                    mappings:
                        name:
                            type: "string"
                        description:
                            type: "string"
                            analyzer: "index_regexp"
                            search_analyzer: "search_regexp"
                        created:
                        price:
                            type: "integer"
                        quantity:
                            type: "integer"
                        status_id:
                            type: "object"
                            properties:
                                name:
                                    type: "string"
                                enabled:
                                    type: "boolean"
                        product_categories:
                            type: "object"
                            properties:
                                name:
                                    type: "string"
                                enabled:
                                    type: "boolean"
                        notes:
                            type: "nested"
                            properties:
                                note:
                                note_category:
                                    type: "object"
                                    properties:
                                        id:
                                            type: "integer"
                                        name:
                                            type: "string"