#fos_elastica:
#    serializer: ~
#    clients:
#        default: { host: elasticsearch, port: 9200 }
#    indexes:
#        workshop:
#            settings:
#                analysis:
#                    filter:
#                        regexp_filter:
#                            type: "ngram"
#                            min_gram: 3
#                            max_gram: 30
#                    analyzer:
#                        index_regexp:
#                            type: "custom"
#                            tokenizer: "whitespace"
#                            filter: ["lowercase", "regexp_filter"]
#                        search_regexp:
#                            type: "custom"
#                            tokenizer: "whitespace"
#                            filter: ["lowercase"]
#            types:
#                shop:
#                    serializer:
#                        groups: ["workshop1"]
#                    persistence:
#                        driver: orm
#                        model: ProductBundle\Entity\Product
#                          #The _all field allows you to search for values in documents
#                          #without knowing which field contains the value.
#                    indexable_callback: 'shouldBeElasticSearchIndexable'
#                    _all:
#                        enabled: false
#
#                    mappings:
#                        #ToDo... ;-)