product_index:
    path:     /
    defaults: { _controller: "ProductBundle:Product:index" }
    methods:  GET

product_show:
    path:     /{id}/show
    defaults: { _controller: "ProductBundle:Product:show" }
    methods:  GET

product_new:
    path:     /new
    defaults: { _controller: "ProductBundle:Product:new" }
    methods:  [GET, POST]

product_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductBundle:Product:edit" }
    methods:  [GET, POST]

product_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductBundle:Product:delete" }
    methods:  DELETE

product_note:
    path:     /{id}/note
    defaults: { _controller: "ProductBundle:Product:note" }
    methods:  POST
